// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder-project.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key';

// Note: We use database-stored sessions instead of localStorage
// Sessions are managed server-side and transmitted via HTTP-only cookies
// This provides better security than localStorage-based sessions

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use custom storage (no localStorage for security)
    storage: {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    },
    persistSession: false,
    autoRefreshToken: false,
  },
});